openapi: 3.0.0
info:
  title: AI Employee Communication API
  description: API for managing AI employee communication channels (Email, LinkedIn, WhatsApp)
  version: 1.0.0

paths:
  /channels:
    get:
      summary: List all communication channels
      responses:
        '200':
          description: List of communication channels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommunicationChannel'

  /channels/{channelId}/messages:
    get:
      summary: Get messages from a specific channel
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
        - name: direction
          in: query
          required: false
          schema:
            type: string
            enum: [inbound, outbound]
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'

    post:
      summary: Send a message through a specific channel
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '200':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Invalid request or approval required
        '429':
          description: Rate limit exceeded

  /approvals:
    post:
      summary: Create an approval request for a sensitive action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApprovalRequest'
      responses:
        '201':
          description: Approval request created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approval'

  /approvals/{approvalId}:
    get:
      summary: Get approval details
      parameters:
        - name: approvalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Approval details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approval'

components:
  schemas:
    CommunicationChannel:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the channel
        name:
          type: string
          description: Name of the channel (e.g., email, linkedin, whatsapp)
        type:
          type: string
          enum: [EMAIL, LINKEDIN, WHATSAPP]
          description: Type of communication channel
        status:
          type: string
          enum: [ACTIVE, INACTIVE, SUSPENDED]
          description: Current operational status
        createdAt:
          type: string
          format: date-time
          description: Timestamp when channel was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when channel was last updated

    Message:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the message
        channelId:
          type: string
          description: ID of the communication channel
        direction:
          type: string
          enum: [INBOUND, OUTBOUND]
          description: Direction of the message
        sender:
          type: string
          description: Identifier of the sender
        recipient:
          type: string
          description: Identifier of the recipient
        content:
          type: string
          description: Content of the message
        subject:
          type: string
          description: Subject line (for email messages)
        status:
          type: string
          enum: [PENDING, SENT, DELIVERED, FAILED]
          description: Current status of the message
        timestamp:
          type: string
          format: date-time
          description: When the message was sent/received
        approvalRequired:
          type: boolean
          description: Whether this message requires approval
        approvalStatus:
          type: string
          enum: [PENDING, APPROVED, REJECTED]
          description: Status of approval if required

    SendMessageRequest:
      type: object
      required:
        - recipient
        - content
      properties:
        recipient:
          type: string
          description: Recipient identifier
        content:
          type: string
          description: Message content
        subject:
          type: string
          description: Subject line (for email messages)
        approvalRequired:
          type: boolean
          description: Whether approval is required before sending

    Approval:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the approval
        messageType:
          type: string
          enum: [EMAIL, MESSAGE, POST]
          description: Type of message requiring approval
        action:
          type: string
          description: Description of the action requiring approval
        recipient:
          type: string
          description: Target recipient of the action
        reason:
          type: string
          description: Justification for the action
        createdTime:
          type: string
          format: date-time
          description: When approval request was created
        expirationTime:
          type: string
          format: date-time
          description: When approval request expires
        status:
          type: string
          enum: [PENDING, APPROVED, REJECTED, EXPIRED]
          description: Current status of the approval

    CreateApprovalRequest:
      type: object
      required:
        - messageType
        - action
        - recipient
        - reason
      properties:
        messageType:
          type: string
          enum: [EMAIL, MESSAGE, POST]
          description: Type of message requiring approval
        action:
          type: string
          description: Description of the action requiring approval
        recipient:
          type: string
          description: Target recipient of the action
        reason:
          type: string
          description: Justification for the action
        amount:
          type: number
          format: decimal
          description: Amount involved (for financial actions)