openapi: 3.0.0
info:
  title: AI Employee Response API
  description: API for managing AI employee response capabilities across communication channels
  version: 1.0.0

paths:
  /responses:
    post:
      summary: Send a response message to a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendResponseRequest'
      responses:
        '201':
          description: Response queued for sending
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '400':
          description: Invalid request or approval required
        '429':
          description: Rate limit exceeded

  /responses/{responseId}:
    get:
      summary: Get response details and status
      parameters:
        - name: responseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '404':
          description: Response not found

  /conversations/{conversationId}/context:
    get:
      summary: Get conversation context
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Conversation context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationContext'
        '404':
          description: Conversation not found

  /approvals:
    post:
      summary: Create an approval request for a response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApprovalRequest'
      responses:
        '201':
          description: Approval request created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApprovalRequest'

  /approvals/{approvalId}/approve:
    post:
      summary: Approve a response for sending
      parameters:
        - name: approvalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response approved and queued for sending
        '400':
          description: Approval request invalid
        '404':
          description: Approval request not found

components:
  schemas:
    SendResponseRequest:
      type: object
      required:
        - originalMessageId
        - channel
        - content
      properties:
        originalMessageId:
          type: string
          description: ID of the original message that triggered this response
        channel:
          $ref: '#/components/schemas/CommunicationChannelEnum'
        recipientIdentifier:
          type: string
          description: Identifier of the recipient
        content:
          type: string
          description: Content of the response message
        responseType:
          $ref: '#/components/schemas/ResponseTypeEnum'
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        approvalRequired:
          type: boolean
          description: Whether this response requires approval before sending

    ResponseMessage:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the response
        originalMessageId:
          type: string
          description: ID of the original message that triggered this response
        channel:
          $ref: '#/components/schemas/CommunicationChannelEnum'
        senderIdentifier:
          type: string
          description: Identifier of the original sender
        recipientIdentifier:
          type: string
          description: Identifier of the recipient
        content:
          type: string
          description: Content of the response message
        responseType:
          $ref: '#/components/schemas/ResponseTypeEnum'
        status:
          $ref: '#/components/schemas/ResponseStatusEnum'
        priority:
          $ref: '#/components/schemas/PriorityEnum'
        approvalRequired:
          type: boolean
          description: Whether this response requires approval
        createdAt:
          type: string
          format: date-time
          description: When the response was created
        sentAt:
          type: string
          format: date-time
          description: When the response was sent (if sent)
        errorMessage:
          type: string
          description: Error message if response failed

    ConversationContext:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the conversation context
        originalChannel:
          $ref: '#/components/schemas/CommunicationChannelEnum'
        originalSender:
          type: string
          description: Sender identifier from original message
        originalMessageId:
          type: string
          description: Platform-specific message ID of original message
        conversationThreadID:
          type: string
          description: Thread identifier for maintaining context
        contextSummary:
          type: string
          description: Brief summary of conversation context
        active:
          type: boolean
          description: Whether the conversation is still active
        createdAt:
          type: string
          format: date-time
          description: When the conversation context was created
        lastActivity:
          type: string
          format: date-time
          description: When the last activity occurred

    ApprovalRequest:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the approval request
        responseMessageId:
          type: string
          description: ID of the response that needs approval
        requestor:
          type: string
          description: Entity requesting approval
        reason:
          type: string
          description: Reason for requiring approval
        createdAt:
          type: string
          format: date-time
          description: When approval request was created
        expiresAt:
          type: string
          format: date-time
          description: When approval request expires
        status:
          $ref: '#/components/schemas/ApprovalStatusEnum'
        approvedBy:
          type: string
          description: Approver identifier (if approved)
        approvedAt:
          type: string
          format: date-time
          description: When the request was approved (if approved)

    CreateApprovalRequest:
      type: object
      required:
        - responseMessageId
        - reason
      properties:
        responseMessageId:
          type: string
          description: ID of the response that needs approval
        reason:
          type: string
          description: Reason for requiring approval

    CommunicationChannelEnum:
      type: string
      enum: [EMAIL, LINKEDIN, WHATSAPP]
      description: Communication channel type

    ResponseTypeEnum:
      type: string
      enum: [INFORMATIONAL, ACTION_REQUEST, STATUS_UPDATE, CONFIRMATION]
      description: Type of response message

    PriorityEnum:
      type: string
      enum: [LOW, MEDIUM, HIGH, CRITICAL]
      description: Priority level for the response

    ResponseStatusEnum:
      type: string
      enum: [QUEUED, SENDING, SENT, FAILED, APPROVAL_REQUIRED]
      description: Status of the response message

    ApprovalStatusEnum:
      type: string
      enum: [PENDING, APPROVED, REJECTED, EXPIRED]
      description: Status of the approval request