openapi: 3.0.0
info:
  title: Silver Tier Task Management API
  description: API for advanced task management in Personal AI Employee Silver Tier
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server

paths:
  /tasks:
    get:
      summary: List all tasks
      description: Retrieve a list of tasks with filtering and pagination options
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [pending, processing, completed, failed, awaiting_approval]
          description: Filter tasks by status
        - name: category
          in: query
          required: false
          schema:
            type: string
            enum: [email, file, calendar, crm, custom]
          description: Filter tasks by category
        - name: source
          in: query
          required: false
          schema:
            type: string
            enum: [gmail, whatsapp, filesystem, calendar, api]
          description: Filter tasks by source
        - name: priority
          in: query
          required: false
          schema:
            type: string
            enum: [low, medium, high, critical]
          description: Filter tasks by priority
        - name: assigned_to
          in: query
          required: false
          schema:
            type: string
          description: Filter tasks by assignee
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
          description: Limit number of results returned
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Offset for pagination
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
    post:
      summary: Create new task
      description: Create a new task in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized

  /tasks/{id}:
    get:
      summary: Get task by ID
      description: Retrieve a specific task by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    put:
      summary: Update task
      description: Update an existing task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '404':
          description: Task not found
    delete:
      summary: Delete task
      description: Delete a task from the system
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found

  /tasks/{id}/retry:
    post:
      summary: Retry failed task
      description: Attempt to retry a failed task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Task ID
      responses:
        '200':
          description: Task retry initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Task cannot be retried
        '404':
          description: Task not found

  /tasks/bulk-update:
    post:
      summary: Bulk update tasks
      description: Update multiple tasks at once
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
                updates:
                  $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Bulk update results
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_count:
                    type: integer
                  failed_count:
                    type: integer
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        task_id:
                          type: string
                          format: uuid
                        error:
                          type: string

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, processing, completed, failed, awaiting_approval]
        priority:
          type: string
          enum: [low, medium, high, critical]
        category:
          type: string
          enum: [email, file, calendar, crm, custom]
        source:
          type: string
          enum: [gmail, whatsapp, filesystem, calendar, api]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        due_date:
          type: string
          format: date-time
        assigned_to:
          type: string
        completed_at:
          type: string
          format: date-time
        metadata:
          type: object
          additionalProperties: true
        parent_task_id:
          type: string
          format: uuid
        estimated_duration:
          type: integer
          description: Estimated duration in minutes
        actual_duration:
          type: integer
          description: Actual duration in minutes
        confidence_score:
          type: number
          format: float
          minimum: 0
          maximum: 1
        retry_count:
          type: integer
          default: 0
        last_error:
          type: string

    CreateTaskRequest:
      type: object
      required:
        - title
        - category
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          type: string
          enum: [pending, processing, awaiting_approval]
          default: pending
        priority:
          type: string
          enum: [low, medium, high, critical]
          default: medium
        category:
          type: string
          enum: [email, file, calendar, crm, custom]
        source:
          type: string
          enum: [gmail, whatsapp, filesystem, calendar, api]
          default: api
        due_date:
          type: string
          format: date-time
        assigned_to:
          type: string
        metadata:
          type: object
          additionalProperties: true
        parent_task_id:
          type: string
          format: uuid
        estimated_duration:
          type: integer
          description: Estimated duration in minutes

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          type: string
          enum: [pending, processing, completed, failed, awaiting_approval]
        priority:
          type: string
          enum: [low, medium, high, critical]
        due_date:
          type: string
          format: date-time
        assigned_to:
          type: string
        metadata:
          type: object
          additionalProperties: true
        estimated_duration:
          type: integer
          description: Estimated duration in minutes